export const enLocalization = {
    "project": {
        "project_0_name": "Frag Pro Shooter",
        "project_0_desc": "Frag Pro Shooter is a mobile FPS with more than 100 million downloads. For this game, I developed new characters and gameplay features. I also made major technical changes so the game could be ported to Nintendo Switch.",
        "project_0_trailer": "https://www.youtube.com/watch?v=V2JWij_YjQw",
        "project_0_download": "https://www.fragthegame.com/",
        "project_0_platform": "iOS, Android, Nintendo Switch",
        "project_1_name": "SUP: Multiplayer Racing Games",
        "project_1_desc": "SUP is an OhBiBi game with more than 50 million installs. For this game, I mainly added or updated plugins and third-party integrations such as ad mediation tools, social SDKs, and analytics.",
        "project_1_trailer": "https://youtu.be/zd2HCAflpls",
        "project_1_download": "https://apps.apple.com/us/app/sup-multiplayer-racing/id1128327441",
        "project_1_platform": "iOS, Android",
        "project_2_name": "Kahiora",
        "project_2_desc": "This is my graduation project, a beat 'em up for PS4. We created it using Unreal Engine 4. In this game, you play as a guardian protecting a temple and its goddess tree.",
        "project_2_trailer": "https://www.youtube.com/watch?v=isZ9-nnw6wA",
        "project_2_download": "https://isart-digital.itch.io/kahiora",
        "project_2_platform": "PC, PS4",
        "project_3_name": "PAC-MAN: Party Royale",
        "project_3_desc": "I worked on this project as a Tool Programmer at Pastagames. I was in charge of building a new version of the level editor.",
        "project_3_trailer": "https://www.youtube.com/watch?v=PkEiVX8J2pI",
        "project_3_download": "https://apps.apple.com/fr/app/pac-man-party-royale/id1465543094",
        "project_3_platform": "iOS, tvOS, macOS",
        "project_4_name": "Write'n'slash",
        "project_4_desc": "A narrative game I made with a small team using Unity for Isart Gameweek in April 2019. You play as a doll trying to become human.",
        "project_4_trailer": "https://www.youtube.com/watch?v=qLCjRk1p_fA",
        "project_4_download": "https://valentinserri.itch.io/writeandslash",
        "project_4_platform": "PC",
        "project_5_name": "Flump vs Humanity",
        "project_5_desc": "A narrative game made with Unreal Engine. In this game, you are an alien discovering the world through the eyes of an unknown species.",
        "project_5_trailer": "https://www.youtube.com/watch?v=fO3sgxdnNvk",
        "project_5_download": "https://drive.google.com/file/d/1WRAaFOmCXPJTG-HHYDEeixxal1MxRj8N/view?usp=sharing",
        "project_5_platform": "PC",
        "project_6_name": "Beetlefield",
        "project_6_desc": "A tactical free-to-play game made with Unity. In this game, you lead a faction of insects determined to safeguard their lands.",
        "project_6_trailer": "https://www.youtube.com/watch?v=mWcZ4teMTcU",
        "project_6_download": "",
        "project_6_platform": "iOS, Android",
        "project_7_name": "PeachAR",
        "project_7_desc": "An AR application for iOS and Android made with Unity. Its purpose is to bring commercial products to life using AR technology.",
        "project_7_trailer": "https://www.youtube.com/watch?v=Ah_kOFotMUk",
        "project_7_download": "https://play.google.com/store/apps/details?id=com.AlliesGames.PeachAR&hl=en",
        "project_7_platform": "iOS, Android",
        "project_8_name": "Ensapia Engineering",
        "project_8_desc": "An AI-powered internal framework I developed to help the company create new services faster by streamlining exploration, prototyping, and technical review.",
        "project_8_trailer": "",
        "project_8_download": "",
        "project_8_platform": "Internal framework"
    },
    "about": {
        "line1" : "My name is Maxence Beaumont, and I am a game programmer. I specialize mainly in tools and gameplay.",
        "line2" : "I mostly develop in C#, Python, C++, and Next.js. I use AI agents to speed up exploration, prototyping, and technical review so I can deliver higher-quality work faster.",
        "line3" : "I graduated from a Master's degree in Game Design and Programming at Isart Digital in Paris, France, in June 2020.",
        "line4" : "If you want to contact me, my email address is contact.maxencebeaumont@gmail.com. You can also send me a message on LinkedIn by clicking the LinkedIn icon."
    },
    "home": {
        "text": "Welcome to my website! Feel free to look around, check out my projects, or contact me if you need more information."
    },
    "navbar": {
        "brand": "Maxence BEAUMONT",
        "about" : "About me",
        "projects" : "Projects",
        "languages" : "Languages"
    }
}