export const frLocalization = {
    "project": {
        "project_0_name": "Frag Pro Shooter",
        "project_0_desc": "Frag Pro Shooter est un FPS mobile avec plus de 100 millions de téléchargements. Pour ce jeu, j'ai développé de nouveaux personnages ainsi que de nouvelles mécaniques de gameplay. J'ai aussi apporté de nombreux changements techniques en vue de son portage sur Nintendo Switch.",
        "project_0_trailer": "https://www.youtube.com/watch?v=V2JWij_YjQw",
        "project_0_download": "https://www.fragthegame.com/",
        "project_0_platform": "iOS, Android, Nintendo Switch",
        "project_1_name": "SUP: Multiplayer Racing Games",
        "project_1_desc": "SUP est un jeu d'OhBiBi, avec plus de 50 millions d'installations. Pour ce jeu, je suis intervenu pour ajouter ou mettre à jour des plugins et des éléments tiers, comme des outils de médiation publicitaire, des SDK sociaux ou des solutions d'analytics.",
        "project_1_trailer": "https://youtu.be/zd2HCAflpls",
        "project_1_download": "https://apps.apple.com/us/app/sup-multiplayer-racing/id1128327441",
        "project_1_platform": "iOS, Android",
        "project_2_name": "Kahiora",
        "project_2_desc": "Il s'agit de mon projet de fin d'études, un beat'em up sur PS4 réalisé avec Unreal Engine 4. Dans ce jeu, vous incarnez une gardienne qui défend un temple et son arbre divin.",
        "project_2_trailer": "https://www.youtube.com/watch?v=isZ9-nnw6wA",
        "project_2_download": "https://isart-digital.itch.io/kahiora",
        "project_2_platform": "PC, PS4",
        "project_3_name": "PAC-MAN: Party Royale",
        "project_3_desc": "J'ai fait partie de ce projet en tant que programmeur outil. J'étais en charge de la mise en place du nouvel éditeur de niveau en C++.",
        "project_3_trailer": "https://www.youtube.com/watch?v=PkEiVX8J2pI",
        "project_3_download": "https://apps.apple.com/fr/app/pac-man-party-royale/id1465543094",
        "project_3_platform": "iOS, tvOS, macOS",
        "project_4_name": "Write'n'slash",
        "project_4_desc": "C'est un jeu narratif que j'ai réalisé avec quelques personnes durant la Gameweek d'Isart 2019, en utilisant Unity.",
        "project_4_trailer": "https://www.youtube.com/watch?v=qLCjRk1p_fA",
        "project_4_download": "https://valentinserri.itch.io/writeandslash",
        "project_4_platform": "PC",
        "project_5_name": "Flump vs Humanity",
        "project_5_desc": "C'est un jeu narratif réalisé avec Unreal Engine 4. Dans ce jeu, vous incarnez un alien et découvrez le monde à travers le regard d'une espèce inconnue.",
        "project_5_download": "https://drive.google.com/file/d/1WRAaFOmCXPJTG-HHYDEeixxal1MxRj8N/view?usp=sharing",
        "project_5_platform": "PC",
        "project_6_name": "Beetlefield",
        "project_6_desc": "Il s'agit d'un tactical sur iOS et Android développé avec Unity. Dans ce jeu, vous incarnez une faction d'insectes qui cherche à sauvegarder ses terres.",
        "project_6_trailer": "https://www.youtube.com/watch?v=mWcZ4teMTcU",
        "project_6_download": "",
        "project_6_platform": "iOS, Android",
        "project_7_name": "PeachAR",
        "project_7_desc": "C'est une application AR sur iOS et Android développée avec Unity. Avec celle-ci, vous pouvez donner vie à vos produits grâce à la réalité augmentée.",
        "project_7_trailer": "https://www.youtube.com/watch?v=Ah_kOFotMUk",
        "project_7_download": "https://play.google.com/store/apps/details?id=com.AlliesGames.PeachAR&hl=en",
        "project_7_platform": "iOS, Android",
        "project_8_name": "Ensapia Engineering",
        "project_8_desc": "Un framework interne propulsé par l'IA que j'ai développé pour aider l'entreprise à créer de nouveaux services plus rapidement, en fluidifiant l'exploration, le prototypage et la relecture technique.",
        "project_8_trailer": "",
        "project_8_download": "",
        "project_8_platform": "Framework interne"
    },
    "about": {
        "line1" : "Je m'appelle Maxence Beaumont et je suis software engineer. Je suis principalement spécialisé dans les outils pour le développement de jeux et l'intelligence artificielle.",
        "line2" : "Je développe principalement en C#, Python, C++ et Next.js. J'utilise des agents IA pour accélérer l'exploration, le prototypage et la relecture technique, afin de livrer des projets de meilleure qualité plus rapidement.",
        "line3" : "Concernant ma formation, j'ai obtenu un mastère en Game Design and Programming à Isart Digital, à Paris, en juin 2020.",
        "line4" : "Si vous souhaitez me contacter, mon adresse est contact.maxencebeaumont@gmail.com. Vous pouvez aussi m'envoyer un message sur LinkedIn en cliquant sur l'icône."
    },
    "home": {
        "text": "Bienvenue sur mon portfolio ! N'hésitez pas à parcourir le site, découvrir mes projets et me contacter si vous souhaitez plus d'informations."
    },
    "navbar": {
        "brand": "Maxence BEAUMONT",
        "about" : "À propos",
        "projects" : "Projets",
        "languages" : "Langues"
    }
}