export const jpLocalization = {
    "project": {
        "project_0_name": "Frag Pro Shooter",
        "project_0_desc": "「Frag Pro Shooter」は、モバイル向けFPSで、1億ダウンロードを超えています。このゲームでは、新しいキャラクターやゲームプレイ機能を開発しました。また、Nintendo Switchへの移植に向けて大きな技術的変更も行いました。",
        "project_0_trailer": "https://www.youtube.com/watch?v=V2JWij_YjQw",
        "project_0_download": "https://www.fragthegame.com/",
        "project_0_platform": "iOS, Android, Nintendo Switch",
        "project_1_name": "SUP: Multiplayer Racing Games",
        "project_1_desc": "「SUP」は、OhBiBiが開発したゲームで、5,000万以上インストールされています。このゲームでは、主にプラグインやサードパーティ製機能（広告配信ツール、ソーシャルSDK、分析ツールなど）の追加・更新を担当しました。",
        "project_1_trailer": "https://youtu.be/zd2HCAflpls",
        "project_1_download": "https://apps.apple.com/us/app/sup-multiplayer-racing/id1128327441",
        "project_1_platform": "iOS, Android",
        "project_2_name": "Kahiora",
        "project_2_desc": "これはPS4向けのベルトスクロールアクションをテーマにした卒業プロジェクトです。Unreal Engine 4を使って開発しました。プレイヤーは、寺院と神木を守る守護者として戦います。",
        "project_2_trailer": "https://www.youtube.com/watch?v=isZ9-nnw6wA",
        "project_2_download": "https://isart-digital.itch.io/kahiora",
        "project_2_platform": "PC, PS4",
        "project_3_name": "PAC-MAN: Party Royale",
        "project_3_desc": "Pastagamesでツールプログラマーとして参加し、新しいレベルエディタの開発を担当しました。",
        "project_3_trailer": "https://www.youtube.com/watch?v=PkEiVX8J2pI",
        "project_3_download": "https://apps.apple.com/fr/app/pac-man-party-royale/id1465543094",
        "project_3_platform": "iOS, tvOS, macOS",
        "project_4_name": "Write'n'slash",
        "project_4_desc": "2019年4月のIsart Gameweekに向けて、Unityで制作したナラティブゲームです。プレイヤーは、人形のように振る舞う存在を操作することになります。",
        "project_4_trailer": "https://www.youtube.com/watch?v=qLCjRk1p_fA",
        "project_4_platform": "PC",
        "project_4_download": "https://valentinserri.itch.io/writeandslash",
        "project_5_name": "Flump vs Humanity",
        "project_5_desc": "Unreal Engineで開発したナラティブゲームです。プレイヤーはエイリアンとなり、未知の種の視点から世界を発見します。",
        "project_5_trailer": "https://www.youtube.com/watch?v=fO3sgxdnNvk",
        "project_5_download": "https://drive.google.com/file/d/1WRAaFOmCXPJTG-HHYDEeixxal1MxRj8N/view?usp=sharing",
        "project_5_platform": "PC",
        "project_6_name": "Beetlefield",
        "project_6_desc": "Unityで開発した無料のタクティカルゲームです。プレイヤーは、自分たちの土地を守るために昆虫の陣営を率います。",
        "project_6_trailer": "https://www.youtube.com/watch?v=mWcZ4teMTcU",
        "project_6_download": "",
        "project_6_platform": "iOS, Android",
        "project_7_name": "PeachAR",
        "project_7_desc": "Unityで制作したiOSおよびAndroid向けのARアプリです。AR技術を活用して、現実の商品に新しい体験を加えることを目的としています。",
        "project_7_trailer": "https://www.youtube.com/watch?v=Ah_kOFotMUk",
        "project_7_download": "https://play.google.com/store/apps/details?id=com.AlliesGames.PeachAR&hl=en",
        "project_7_platform": "iOS, Android",
        "project_8_name": "Ensapia Engineering",
        "project_8_desc": "AIを活用した社内向けフレームワークで、探索、試作、技術レビューを効率化し、会社の新しいサービス開発をより速く進められるようにしました。",
        "project_8_trailer": "",
        "project_8_download": "",
        "project_8_platform": "社内フレームワーク"
    },
    "about": {
        "line1" : "私の名前はマクサンス・ボーモンです。ゲームプログラマーとして、主にツールとゲームプレイを担当しています。",
        "line2" : "主にC#、Python、C++、Next.jsで開発しています。AIエージェントを使って、調査、試作、技術レビューを素早く進め、より高品質な成果をより早く届けられるようにしています。",
        "line3" : "2020年6月に、フランス・パリのIsart Digitalでゲームデザインとプログラミングの修士課程を修了しました。",
        "line4" : "ご連絡は contact.maxencebeaumont@gmail.com までお願いします。LinkedInアイコンからもメッセージを送っていただけます。"
    },
    "home": {
        "text": "ウェブサイトへようこそ。ぜひプロジェクトをご覧いただき、詳細が必要でしたらお気軽にお問い合わせください。"
    },
    "navbar": {
        "brand": "BEAUMONT MAXENCE",
        "about" : "自己紹介",
        "projects" : "プロジェクト",
        "languages" : "言語"
    }
}