export const koLocalization = {
    "project": {
        "project_0_name": "Frag Pro Shooter",
        "project_0_desc": "Frag Pro Shooter는 모바일 FPS 게임으로, 1억 회 이상 다운로드되었습니다. 이 게임에서 저는 새로운 캐릭터와 게임플레이 기능을 개발했고, Nintendo Switch로 이식할 수 있도록 중요한 기술적 변경도 진행했습니다.",
        "project_0_trailer": "https://www.youtube.com/watch?v=V2JWij_YjQw",
        "project_0_download": "https://www.fragthegame.com/",
        "project_0_platform": "iOS, Android, Nintendo Switch",
        "project_1_name": "SUP: Multiplayer Racing Games",
        "project_1_desc": "SUP는 OhBiBi의 게임으로, 5천만 회 이상의 설치 수를 기록했습니다. 이 프로젝트에서는 광고 중재 도구, 소셜 SDK, 분석 도구와 같은 플러그인 및 서드파티를 추가하거나 업데이트하는 작업을 주로 맡았습니다.",
        "project_1_trailer": "https://youtu.be/zd2HCAflpls",
        "project_1_download": "https://apps.apple.com/us/app/sup-multiplayer-racing/id1128327441",
        "project_1_platform": "iOS, Android",
        "project_2_name": "Kahiora",
        "project_2_desc": "이 작품은 PS4용 벨트스크롤 액션 게임을 주제로 한 졸업 프로젝트입니다. Unreal Engine 4로 개발했으며, 플레이어는 사원과 신성한 나무를 지키는 수호자가 됩니다.",
        "project_2_trailer": "https://www.youtube.com/watch?v=isZ9-nnw6wA",
        "project_2_download": "https://isart-digital.itch.io/kahiora",
        "project_2_platform": "PC, PS4",
        "project_3_name": "PAC-MAN: Party Royale",
        "project_3_desc": "Pastagames의 툴 프로그래머로 참여해, 새로운 버전의 레벨 에디터를 만드는 작업을 담당했습니다.",
        "project_3_trailer": "https://www.youtube.com/watch?v=PkEiVX8J2pI",
        "project_3_download": "https://apps.apple.com/fr/app/pac-man-party-royale/id1465543094",
        "project_3_platform": "iOS, tvOS, macOS",
        "project_4_name": "Write'n'slash",
        "project_4_desc": "Unity를 사용해 2019년 4월 Isart Gameweek를 위해 여러 사람과 함께 만든 내러티브 게임입니다. 플레이어는 인간이 되려고 하는 인형을 조종하게 됩니다.",
        "project_4_trailer": "https://www.youtube.com/watch?v=qLCjRk1p_fA",
        "project_4_download": "https://valentinserri.itch.io/writeandslash",
        "project_4_platform": "PC",
        "project_5_name": "Flump vs Humanity",
        "project_5_desc": "Unreal Engine으로 만든 내러티브 게임입니다. 이 게임에서 당신은 외계인이 되어, 미지의 종족의 시선으로 세상을 탐험하게 됩니다.",
        "project_5_trailer": "https://www.youtube.com/watch?v=fO3sgxdnNvk",
        "project_5_download": "https://drive.google.com/file/d/1WRAaFOmCXPJTG-HHYDEeixxal1MxRj8N/view?usp=sharing",
        "project_5_platform": "PC",
        "project_6_name": "Beetlefield",
        "project_6_desc": "Unity로 만든 무료 플레이 전술 게임입니다. 이 게임에서 당신은 자신의 영토를 지키려는 곤충 진영을 이끌게 됩니다.",
        "project_6_trailer": "https://www.youtube.com/watch?v=mWcZ4teMTcU",
        "project_6_download": "",
        "project_6_platform": "iOS, Android",
        "project_7_name": "PeachAR",
        "project_7_desc": "Unity로 제작된 iOS 및 Android용 AR 애플리케이션입니다. AR 기술을 사용해 상용 제품에 생동감을 불어넣는 것이 목적입니다.",
        "project_7_trailer": "https://www.youtube.com/watch?v=Ah_kOFotMUk",
        "project_7_download": "https://play.google.com/store/apps/details?id=com.AlliesGames.PeachAR&hl=en",
        "project_7_platform": "iOS, Android",
        "project_8_name": "Ensapia Engineering",
        "project_8_desc": "탐색, 프로토타이핑, 기술 검토를 효율화하여 회사가 새로운 서비스를 더 빠르게 만들 수 있도록 개발한 AI 기반 내부 프레임워크입니다.",
        "project_8_trailer": "",
        "project_8_download": "",
        "project_8_platform": "내부 프레임워크"
    },
    "about": {
        "line1" : "제 이름은 Maxence Beaumont이며, 저는 게임 프로그래머입니다. 주로 툴과 게임플레이를 전문으로 합니다.",
        "line2" : "주로 C#, Python, C++, Next.js로 개발합니다. AI 에이전트를 활용해 탐색, 프로토타이핑, 기술 검토를 더 빠르게 진행하고, 더 높은 품질의 결과물을 더 빨리 내고 있습니다.",
        "line3" : "학력으로는 2020년 6월 프랑스 파리의 Isart Digital에서 게임 디자인 및 프로그래밍 석사 과정을 졸업했습니다.",
        "line4" : "연락을 원하시면 contact.maxencebeaumont@gmail.com 으로 메일을 보내주시거나, LinkedIn 아이콘을 클릭해 제 프로필로 이동하실 수 있습니다."
    },
    "home": {
        "headline": "게임 툴, AI 워크플로, 기술 방향 설계.",
        "text": "제 웹사이트에 오신 것을 환영합니다! 자유롭게 둘러보시고, 제 프로젝트를 살펴보거나 추가 정보가 필요하시면 연락해 주세요.",
        "subtext": "팀이 더 빠르게 움직이면서도 높은 품질을 유지할 수 있도록 돕는 도구와 시스템을 만듭니다."
    },
    "navbar": {
        "brand": "Maxence BEAUMONT",
        "about" : "소개",
        "projects" : "프로젝트",
        "languages" : "언어"
    }
}